### ISSUE TITLE
about temporalsoften

### ISSUE THREAD

**Issue by sl1pkn07** [IFeelBloated/TemporalSoften#2]
Hi

You temporalsoften is like this? https://github.com/dubhater/vapoursynth-temporalsoften

or is different thing

greetings

**Comment by IFeelBloated** [comment]
same stuff with additional floating point support

**Comment by sl1pkn07** [comment]
then is a replacement?

**Comment by IFeelBloated** [comment]
yeah

**Comment by sl1pkn07** [comment]
tnx for the info
